name: Test minimum required python version

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install vermin
    - name: Test minimum required python version
      run: |
        function check_version() {
          local version=$1
          local major_version=${version:0:1}
          if [[ major_version -eq "3" ]]; then
            echo "major version is 3"
            local minor_version=${version:2}
            if [ $minor_version -lt "7" ]; then
              echo "minor version is ${minor_version}; passed"
            else
              exit 127
            fi
          else
            echo "major version is 2; passed"
          fi
        }

        min_version=`vermin --no-tips --no-parse-comments ./ | grep "Minimum required versions: "`
        check_version ${min_version:27}
